site_name: Hadi Javeed's blog
site_author: Hadi Javeed
site_description: >-
  Notes about startups, AI, health-care and overall engineering
repo_name: blog
site_url: https://hadijaveed.github.io/personal-blog
theme:
  name: material
  features:
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.expand
    - navigation.indexes
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.top
    - navigation.tracking
    # - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  language: en
  palette: 
    # Palette toggle for light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - social
  - glightbox
  - search
  - blog:
      blog_dir: .
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/hadijaveed
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hadijpk
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hadijaveed

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
# icon:
#   logo: logo
nav:
  - Thoughts:
    - index.md
  - About me:
    - "about.md"
  - Subscribe:
    - "https://hjaveed.substack.com/subscribe"

  # - Writing:
  #   - "writing/index.md"
  # - Hiring:
  #   - Working with me: "hiring.md"
  #   - Sample Proposal: "assessment.md"
  # - Contact: 'contact.md'

copyright: |
  &copy; 2024 <a href="https://github.com/hadijaveed"  target="_blank" rel="noopener">Hadi Javeed</a>