authors:
  hjaveed:
    name: Hadi Javeed
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/10227760?v=5
    url: https://www.linkedin.com/in/hadijaveed/
  christian:
    name: Christian Pean
    description: Co-Author
    avatar: https://media.licdn.com/dms/image/v2/D4E03AQFaXhjOk0SUfw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1703386233582?e=1762387200&v=beta&t=gahTty433KKv4K9d6eEtudGiXC__uQU3fPRdGFdQtgg
    url: https://www.linkedin.com/in/christianpean/

