authors:
  hjaveed:
    name: Hadi Javeed
    description: Creator
    avatar: https://media.licdn.com/dms/image/D4D03AQGYRXyJr-2YOg/profile-displayphoto-shrink_400_400/0/1668653124279?e=1712188800&v=beta&t=mdEjdud189XFRf3lgOKtU2IEme16o2Zst9kqRK9JZq4
    url: https://www.linkedin.com/in/hadijaveed/